### PR TITLE
fix: [#285] Use Implicit Tiled layer order to default z index

### LINKED ISSUE #285: Tiled layer order should help decide zIndex
Right now the plugin **needs** us to specify a zindex property for individual inserted objects (and colliders). Tiled already provides it's own sorting system for layers. These layers are saved in order to a .tmx or .json file.

### Steps to Reproduce

1. Create a map in tiled with **at least 2 tile layers and one or more object layers**. (at least 2, because [tile layers start at z index -1](https://github.com/excaliburjs/excalibur-tiled/blob/02c122a11f3737928d9d19db3b3b77e6895c6196/src/tiled-map-resource.ts#L60))
2. **Sort the layers** so the objects are above the tile layers
3. Create an **inserted object (or collider)** in one of the top object layers.
_For demonstration purposes I've positioned a fire (child of AnimatedFire layer) on top of the fireplace (child of Overlay1 layer):_
image
3. Load the map in the way described in the README

### Expected Result
I would expect the Tiled layer sorting to help this plugin decide the z index for the actors. [Currently for tiles a z index is automatically decided](https://github.com/excaliburjs/excalibur-tiled/blob/02c122a11f3737928d9d19db3b3b77e6895c6196/src/tiled-map-resource.ts#L435), but this is not the actual order as the layer occurs in the map file. For [actors](https://github.com/excaliburjs/excalibur-tiled/blob/02c122a11f3737928d9d19db3b3b77e6895c6196/src/tiled-map-resource.ts#L185) and [colliders](https://github.com/excaliburjs/excalibur-tiled/blob/02c122a11f3737928d9d19db3b3b77e6895c6196/src/tiled-map-resource.ts#L124) an absolute zindex (specified in the property of the object) is needed.

### Actual Result

The z index of the actor is unchanged (therefor 0) because no property is set. This causes the tiles to overlap the actor. [(The tiles have their z index automatically decided starting from -1)](https://github.com/excaliburjs/excalibur-tiled/blob/02c122a11f3737928d9d19db3b3b77e6895c6196/src/tiled-map-resource.ts#L435)
image

### Current Workaround

Manually set a zindex property on each object and tile layers (this is how the examples in `./examples` avoid this problem)

### Proposed fix
Sadly I'm not motivated enough to create a PR, though I hope I can still aid you with a (hopefully) clear bug report and proposed fix:

* The .tmx file contains all tile and object layers in order
* [This code would require a substantial change](https://github.com/excaliburjs/excalibur-tiled/blob/02c122a11f3737928d9d19db3b3b77e6895c6196/src/tiled-map.ts#L96)
* The map file would have to be parsed preserving the order of the nodes
* The layer's default zIndex would be it's offset from the first layer node

### Should this be fixed?
In my opinion: eventually yes. Because:
* The sorting is respected by the Tiled map editor. 
* The behavior intuitive.
* When I didn't see my objects in-game it took me a good couple minutes to realize that it was not something I was doing wrong.
* With more objects comes more manual management of z indexes, which can be tedious

However looking at the amount of work that is required to fix this, the workaround seems a viable alternative for now.

I really hope this helps you all. 

Thanks for your time and effort!

### PR DESCRIPTION
**Pull request by eonarheim**
Closes #285

This PR implements implicit z-ordering based on the Tiled editor order. Z-index can still be overridden with a custom property if desired. The first layer will start at `-1` z-index (the previous default) and will increment based on the Tiled order.

Example of inserted tiles using the implicit z-index, no more custom property!
implicit-z

Small-ish breaking change that moves all the optional properties to an option bag in the constructor

```typescript

// New constructor
const map = new TiledMapResource('path/to/map.tmx', { firstLayerZIndex: -2 });

// Old constructor
const map = new TiledMapResource('path/to/map.tmx', undefined, -2);
```

TODOs before merge:
* [x] Tests
* [x] @kamranayub @jedeen Feedback on the ctor?

### CODE REVIEW

**Comment by kamranayub** [comment]
Oh yeah I prefer the new constructor for sure

File: example/game.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ const start = (mapFile: string) => {
    }
    game.add(player);
 
-   const map = new TiledMapResource(mapFile);
+   const map = new TiledMapResource(mapFile, { firstLayerZIndex: -2 });
```
Comment (kamranayub) [inline example/game.ts:61]: 👍

File: src/tiled-map-resource.ts [hunk 2]
```diff
@@ -42,6 +42,18 @@ export enum TiledMapFormat {
    JSON = 'JSON'
 }
 
+export interface TiledMapOptions {
+   /**
+    * Optionally override the map format, by default files ending in .tmx are treated as TMX format, otherise treated as JSON format
```
Comment (kamranayub) [inline src/tiled-map-resource.ts:47]:
```suggestion
    * By default files ending in .tmx are treated as TMX format, otherwise treated as JSON format
```

Shortened (option name is clear), fixed typo

File: src/tiled-map-resource.ts [hunk 3]
```diff
@@ -42,6 +42,18 @@ export enum TiledMapFormat {
...
+    */
+   mapFormatOverride?: TiledMapFormat;
+
+   /**
+    * Optionally Specify the first layer z-index value, each layer will increment up 1 unless overridden (default -1)
```
Comment (kamranayub) [inline src/tiled-map-resource.ts:52]: I'm not sure about the name. Is this number more accurately the starting z-index for auto incrementing values? If the first layer overrides it's z-index, this is confusingly named.

```suggestion
    * Override the starting auto-incrementing z-index value (default: `-1`). Each layer will increment this number by 1 unless the layer specifies it's own custom `zindex` property.
```

File: src/tiled-map-resource.ts [hunk 4]
```diff
@@ -42,6 +42,18 @@ export enum TiledMapFormat {
...
+    */
+   firstLayerZIndex?: number;
```
Comment (kamranayub) [inline src/tiled-map-resource.ts:54]: See above

```suggestion
   startingLayerAutoIncrementingZIndex?: number;
```

File: src/tiled-map-resource.ts [hunk 5]
```diff
@@ -146,46 +166,48 @@ export class TiledMapResource implements Loadable<TiledMap> {
...
+                  });
+                  actor.addComponent(new TiledObjectComponent(tile));
+                  if (Flags.isEnabled('use-legacy-drawing')) {
+                     actor.addDrawing(Sprite.toLegacySprite(sprite));
+                  } else {
+                     actor.graphics.anchor = vec(0, 1);
+                     actor.graphics.use(sprite);
+                  }
+                  scene.add(actor);
+                  const z = tile.getProperty<number>('zindex')?.value ?? (objectLayer.rawObjectGroup.order + this._layerZIndexStart);
```
Comment (kamranayub) [inline src/tiled-map-resource.ts:207]: Is `z` supported too? Or is that reserved by Tiled?

File: src/tiled-map-resource.ts [hunk 6]
```diff
@@ -231,49 +253,53 @@ export class TiledMapResource implements Loadable<TiledMap> {
...
+               const collisionType = box.getProperty<CollisionType>('collisiontype');
+               const color = box.getProperty<string>('color');
+               const zIndex = box.getProperty<number>('zindex')?.value ?? (objectLayer.rawObjectGroup.order + this._layerZIndexStart);
+               ex.colliders.push({
+                  ...box,
+                  width: +(box.width ?? 0),
+                  height: +(box.height ?? 0),
+                  collisionType: collisionType?.value ?? CollisionType.Fixed,
+                  color,
+                  zIndex: zIndex,
```
Comment (kamranayub) [inline src/tiled-map-resource.ts:278]: Does this need to be coerced to int? When a custom value exists, it gets passed raw it looks like. Speaks to extracting a helper to handle getting this value vs. passing raw from `getProperty` otherwise it's easy to miss.

File: src/tiled-map-resource.ts [hunk 7]
```diff
@@ -231,49 +253,53 @@ export class TiledMapResource implements Loadable<TiledMap> {
...
+               var collisionType = circle.getProperty<CollisionType>('collisiontype');
+               var color = circle.getProperty<string>('color');
+               var zIndex = circle.getProperty<number>('zindex')?.value ?? (objectLayer.rawObjectGroup.order + this._layerZIndexStart);
+               ex.colliders.push({
+                  x: circle.x,
+                  y: circle.y,
+                  radius: Math.max(circle.width ?? 0, circle.height ?? 0),
+                  collisionType: collisionType?.value ?? CollisionType.Fixed,
+                  color,
+                  zIndex: zIndex,
```
Comment (kamranayub) [inline src/tiled-map-resource.ts:296]: See above

File: src/tiled-map-resource.ts [hunk 8]
```diff
@@ -440,7 +466,7 @@ export class TiledMapResource implements Loadable<TiledMap> {
             const tileMapLayer = new TileMap(0, 0, this.data.rawMap.tilewidth, this.data.rawMap.tileheight, this.data.height, this.data.width);
             tileMapLayer.addComponent(new TiledLayerComponent(layer));
 
-            const zindex = getProperty<number>(rawLayer.properties, 'zindex')?.value || layerZIndexBase++;
+            const zindex = getProperty<number>(rawLayer.properties, 'zindex')?.value ?? (layer.rawLayer.order + layerZIndexBase);
```
Comment (kamranayub) [inline src/tiled-map-resource.ts:469]: This is the 3rd or 4th time I've seen this code, candidate to refactor and extract into helper. Note this one also does not coerce when setting 😊

File: src/tiled-map.ts [hunk 9]
```diff
@@ -197,6 +197,12 @@ export class TiledMap {
       resultMap.tileWidth = +rawMap.tilewidth;
       resultMap.tileHeight = +rawMap.tileheight;
 
+      // Tag the raw layers with their original order
```
Comment (kamranayub) [inline src/tiled-map.ts:200]: Extract into named function

**Review by kamranayub — DISMISSED** [review]
Looks pretty good. Left some suggestions to improve clarity and making property handling consistent for z index values.

File: src/tiled-map-resource.ts (hunk 4 above)
Comment (eonarheim) [reply src/tiled-map-resource.ts:54]: This doesn't really influence the auto increment, just the starting z-index. Previously it ways named `layerZIndexStart` which is maybe better?

You suggestion is more descriptive, is there a more terse description? Maybe `initalLayerZIndex`, `startingLayerZIndex`, or go back to the original name?

File: src/tiled-map-resource.ts (hunk 5 above)
Comment (eonarheim) [reply src/tiled-map-resource.ts:207]: I can't recall why, it appears to work in latest Tiled when I checked. Originally we went with "zindex" named custom property for some reason (maybe out of fear of it being reserved or colliding?).

I think it's definitely more ergonomic, with the helper suggestion we could easily add support for custom properties named "z" and "zindex"

File: src/tiled-map-resource.ts (hunk 8 above)
Comment (eonarheim) [reply src/tiled-map-resource.ts:469]: Good call, that's a good refactoring

File: src/tiled-map-resource.ts (hunk 6 above)
Comment (eonarheim) [reply src/tiled-map-resource.ts:278]: I'll make the helper coerce the type, but it's definitely good to do 👍

File: src/tiled-map-resource.ts (hunk 4 above)
Comment (kamranayub) [reply src/tiled-map-resource.ts:55]: Ah I see! I think either of those are fine, `startingLayerZIndex` is succint and descriptive and `starting` implies it starts a sequence where as `initial` seems static.

Comment (kamranayub) [reply src/tiled-map-resource.ts:55]:
```suggestion
   startingLayerZIndex?: number;
```

File: src/tiled-layer.ts [hunk 10]
```diff
@@ -78,8 +78,29 @@ export class TiledLayer extends TiledEntity {
     */
    public compression?: TiledCompression;
```
Comment (kamranayub) [inline src/tiled-layer.ts:79]: Are the other class members here aligned correctly?

File: src/tiled-layer.ts [hunk 11]
```diff
@@ -78,8 +78,29 @@ export class TiledLayer extends TiledEntity {
...
 
+   /**
+    * Original order of the Tiled layer
+    */
+   public order!: number;
+
    /**
     * Reference to the raw tiled layer data
     */
    public rawLayer!: RawTiledLayer;
```
Comment (kamranayub) [inline src/tiled-layer.ts:89]: Here too

File: src/tiled-layer.ts [hunk 12]
```diff
@@ -78,8 +78,29 @@ export class TiledLayer extends TiledEntity {
...
+
+   public static parse(layer: RawTiledLayer): TiledLayer {
+      if (layer.type !== 'tilelayer') throw Error('Cannot parse a non tilelayer type layer');
+      const resultLayer = new TiledLayer();
+      resultLayer.id = +layer.id;
```
Comment (kamranayub) [inline src/tiled-layer.ts:94]: I get this is a clever way to coerce but it's not clear what this does at first glance especially for someone not as familiar with hacks in JS.

Might as well use the standard, it's available in all browsers we support and it's clearer.


```suggestion
      resultLayer.id = Number.parseInt(layer.id);
```

Note radix is optional and is 10 by default anyway!

Note also that there was code before that didn't coerce, because this one character can get lost in the noise.

File: src/tiled-map-resource.ts [hunk 13]
```diff
@@ -411,18 +438,27 @@ export class TiledMapResource implements Loadable<TiledMap> {
       throw new Error(`Could not find sprite for gid: [${gid}] normalized gid: [${normalizedGid}]`);
    }
 
+   private _calculateZIndex(entity: TiledEntity, tileLayerOrObjectGroup: TiledLayer | TiledObjectGroup): number {
+      let finalZ = entity.getProperty<number>('z')?.value ?? entity.getProperty<number>('zindex')?.value;
+
+      finalZ ??= (tileLayerOrObjectGroup.order + this._layerZIndexStart);
+
+      // coerce to integer
+      return +finalZ
```
Comment (kamranayub) [inline src/tiled-map-resource.ts:447]:
```suggestion
      return Number.parseInt(finalZ);
```

😁

**Review by kamranayub — APPROVED** [review]
I won't block on these suggestions but I do think they make the code intent clear.
